# Generated by Django 5.2.3 on 2025-06-25 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="ФИО")),
                (
                    "teacher_type",
                    models.CharField(
                        choices=[("Внутр", "Внутр"), ("Шт", "Шт")],
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Должность"),
                ),
                ("rate", models.CharField(max_length=10, verbose_name="Ставка")),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Степень"
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Звание"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Почта"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="День рождения"
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Домашний адрес"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
