# Generated by Django 5.2.3 on 2025-06-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=255)),
                ('course', models.IntegerField(blank=True, null=True)),
                ('group_count', models.IntegerField(blank=True, null=True)),
                ('student_count', models.IntegerField(blank=True, null=True)),
                ('lectures', models.FloatField(blank=True, null=True)),
                ('practicals', models.FloatField(blank=True, null=True)),
                ('labs', models.FloatField(blank=True, null=True)),
                ('project_work', models.FloatField(blank=True, null=True)),
                ('consultations', models.FloatField(blank=True, null=True)),
                ('tests', models.FloatField(blank=True, null=True)),
                ('exams', models.FloatField(blank=True, null=True)),
                ('review_distance', models.FloatField(blank=True, null=True)),
                ('practice_supervision', models.FloatField(blank=True, null=True)),
                ('visit_control', models.FloatField(blank=True, null=True)),
                ('qualification_supervision', models.FloatField(blank=True, null=True)),
                ('committee_work', models.FloatField(blank=True, null=True)),
                ('exam_commission', models.FloatField(blank=True, null=True)),
                ('phd_supervision', models.FloatField(blank=True, null=True)),
                ('org_srs', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('total_plan', models.FloatField(blank=True, null=True)),
                ('total_actual', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
