# Generated by Django 5.2.3 on 2025-06-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_educationalmethodicalwork"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="educationalmethodicalwork",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="educationalmethodicalwork",
            name="completed",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Отметка о выполнении"
            ),
        ),
    ]
