# Generated by Django 5.2.3 on 2025-06-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_educationalmethodicalwork_is_completed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationalMethodicalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Наименование работы")),
                (
                    "start_date",
                    models.CharField(max_length=100, verbose_name="Начало работы"),
                ),
                (
                    "end_date",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Окончание работы",
                    ),
                ),
                (
                    "completed",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Отметка о выполнении",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_methods",
                        to="main.teacher",
                    ),
                ),
            ],
        ),
    ]
