# Generated by Django 5.2.3 on 2025-07-01 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_researchwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractResearchWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.TextField(verbose_name="Наименование темы, шифр")),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Должность по НИР"),
                ),
                ("start_date", models.DateField(verbose_name="Начало")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Окончание"),
                ),
                (
                    "completed",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Отметка о выполнении"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
                    ),
                ),
            ],
        ),
    ]
