# Generated by Django 5.2.3 on 2025-07-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_contractresearchwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScientificMethodicalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.TextField(verbose_name="Наименование темы, этап, задание"),
                ),
                ("start_date", models.CharField(max_length=100, verbose_name="Начало")),
                (
                    "end_date",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Окончание"
                    ),
                ),
                (
                    "completed",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Отметка о выполнении",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scientific_methods",
                        to="main.teacher",
                    ),
                ),
            ],
        ),
    ]
