# Generated by Django 5.2.3 on 2025-07-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sciresearchwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование работы')),
                ('job', models.TextField(max_length=100, verbose_name='Должность по НИР')),
                ('start_date', models.CharField(max_length=100, verbose_name='Начало работы')),
                ('end_date', models.CharField(max_length=100, verbose_name='Окончание работы')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Отметка о выполнении')),
            ],
        ),
    ]
