# Generated by Django 5.2.3 on 2025-07-03 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_scimethodicalwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialEducationalWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Наименование работы")),
                (
                    "completed",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отметка о выполнении"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_works",
                        to="main.teacher",
                    ),
                ),
            ],
        ),
    ]
