# Generated by Django 5.2.3 on 2025-07-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_socialeducationalwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("content", models.TextField(verbose_name="Содержание замечаний")),
                (
                    "signature",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Роспись проверяющего"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="main.teacher",
                    ),
                ),
            ],
        ),
    ]
