# Generated by Django 5.2.3 on 2025-07-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_teacherremark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherremark",
            name="signature",
        ),
    ]
