# Generated by Django 5.2.3 on 2025-07-03 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_teacherremark_signature"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualificationImprovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("place", models.CharField(max_length=255, verbose_name="Место")),
                (
                    "document_number",
                    models.CharField(max_length=100, verbose_name="Номер документа"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "duration",
                    models.CharField(max_length=100, verbose_name="Срок прохождения"),
                ),
                ("volume", models.CharField(max_length=100, verbose_name="Объём")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="main.teacher",
                    ),
                ),
            ],
        ),
    ]
