# Generated by Django 5.2.3 on 2025-07-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_qualificationimprovement"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QualificationImprovement",
            new_name="QualificationUpgrade",
        ),
        migrations.RenameField(
            model_name="qualificationupgrade",
            old_name="place",
            new_name="location",
        ),
    ]
