# Generated by Django 5.2.3 on 2025-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_qualificationimprovement_qualificationupgrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedSciWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='№ п/п')),
                ('job', models.TextField(max_length=100, verbose_name='Наименование и вид работы')),
                ('start_date', models.TextField(max_length=100, verbose_name='Выходные данные')),
                ('end_date', models.TextField(max_length=100, verbose_name='Объем в п.л.')),
                ('status', models.TextField(blank=True, max_length=100, verbose_name='Соавторы')),
            ],
        ),
    ]
