# Generated by Django 5.2.3 on 2025-07-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_publicwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(verbose_name='Дата')),
                ('remark', models.TextField(max_length=100, verbose_name='Содержание замечаний')),
                ('signature', models.TextField(max_length=100, verbose_name='Роспись проверяющего')),
            ],
        ),
    ]
