# Generated by Django 5.2.3 on 2025-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(verbose_name='Дата')),
                ('form', models.TextField(max_length=100, verbose_name='Форма повышения квалификации')),
                ('mark', models.TextField(max_length=100, verbose_name='Отметка о выполнении')),
            ],
        ),
    ]
