# Generated by Django 5.2.3 on 2025-07-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_raising'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recom', models.TextField(verbose_name='Рекомендация кафедры по избранию преподавателя')),
            ],
        ),
    ]
