# Generated by Django 4.2.23 on 2025-07-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsem',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_sems', to='main.teacher'),
            preserve_default=False,
        ),
    ]
