# Generated by Django 4.2.23 on 2025-07-03 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_firstsem_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondsem',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_sems', to='main.teacher'),
            preserve_default=False,
        ),
    ]
