# Generated by Django 4.2.23 on 2025-07-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_secondsem_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedsciwork',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='published_sci_work', to='main.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raising',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raising', to='main.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='main.teacher'),
            preserve_default=False,
        ),
    ]
