# Generated by Django 5.2.3 on 2025-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_publishedsciwork_teacher_raising_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationalmethodicalwork",
            name="academic_year",
            field=models.CharField(
                default="2024–2025", max_length=9, verbose_name="Учебный год"
            ),
        ),
    ]
