# Generated by Django 5.2.4 on 2025-07-06 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_educationalmethodicalwork_academic_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_edit_publications", models.BooleanField(default=False)),
                ("can_edit_ip", models.BooleanField(default=False)),
                ("can_edit_pps", models.BooleanField(default=False)),
                ("can_edit_org_work", models.BooleanField(default=False)),
                ("can_edit_sci_work", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
