# Generated by Django 5.2.3 on 2025-07-08 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_accesslevel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_edit_publications",
                    models.BooleanField(
                        default=False, verbose_name="Может редактировать публикации"
                    ),
                ),
                (
                    "can_edit_ip",
                    models.BooleanField(
                        default=False,
                        verbose_name="Может редактировать индивидуальный план",
                    ),
                ),
                (
                    "can_edit_pps",
                    models.BooleanField(
                        default=False, verbose_name="Может редактировать ППС"
                    ),
                ),
                (
                    "can_edit_org_work",
                    models.BooleanField(
                        default=False, verbose_name="Может редактировать орг. работу"
                    ),
                ),
                (
                    "can_edit_sci_work",
                    models.BooleanField(
                        default=False, verbose_name="Может редактировать научную работу"
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="main.teacher",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="AccessLevel",
        ),
    ]
