# Generated by Django 5.2.3 on 2025-07-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_teacherpermission_delete_accesslevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherpermission",
            name="can_manage_accounts",
            field=models.BooleanField(default=False),
        ),
    ]
