# Generated by Django 5.2.3 on 2025-07-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_teacherpermission_can_manage_accounts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherpermission",
            name="can_edit_org_work",
        ),
        migrations.RemoveField(
            model_name="teacherpermission",
            name="can_edit_publications",
        ),
        migrations.RemoveField(
            model_name="teacherpermission",
            name="can_edit_sci_work",
        ),
        migrations.AlterField(
            model_name="teacherpermission",
            name="can_edit_ip",
            field=models.BooleanField(
                default=False, verbose_name="Может редактировать уровни доступа"
            ),
        ),
        migrations.AlterField(
            model_name="teacherpermission",
            name="can_manage_accounts",
            field=models.BooleanField(
                default=False, verbose_name="Может управлять пользователями"
            ),
        ),
    ]
