# Generated by Django 5.2.3 on 2025-07-10 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_remove_teacherpermission_can_edit_org_work_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeachingLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discipline", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=10)),
                ("groups", models.CharField(max_length=10)),
                ("students", models.CharField(max_length=10)),
                ("lectures", models.FloatField(blank=True, null=True)),
                ("practice", models.FloatField(blank=True, null=True)),
                ("labs", models.FloatField(blank=True, null=True)),
                ("coursework", models.FloatField(blank=True, null=True)),
                ("consultations", models.FloatField(blank=True, null=True)),
                ("exams", models.FloatField(blank=True, null=True)),
                ("review_work", models.FloatField(blank=True, null=True)),
                ("practice_supervision", models.FloatField(blank=True, null=True)),
                ("thesis_supervision", models.FloatField(blank=True, null=True)),
                ("gak", models.FloatField(blank=True, null=True)),
                ("admission", models.FloatField(blank=True, null=True)),
                ("phd_supervision", models.FloatField(blank=True, null=True)),
                ("org_work", models.FloatField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
