# Generated by Django 5.2.3 on 2025-07-10 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_teachingload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachingload",
            name="admission",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="consultations",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="coursework",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="exams",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="gak",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="groups",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="labs",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="lectures",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="org_work",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="phd_supervision",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="practice",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="practice_supervision",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="rating",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="review_work",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="students",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="teachingload",
            name="thesis_supervision",
            field=models.FloatField(default=0),
        ),
    ]
