# Generated by Django 4.2.23 on 2025-07-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_teachingload_admission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishedsciwork',
            old_name='status',
            new_name='autors',
        ),
        migrations.RenameField(
            model_name='publishedsciwork',
            old_name='start_date',
            new_name='output',
        ),
        migrations.RenameField(
            model_name='publishedsciwork',
            old_name='end_date',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='publishedsciwork',
            old_name='job',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='publishedsciwork',
            name='name',
        ),
    ]
