# Generated by Django 5.2.3 on 2025-07-14 10:45

from django.db import migrations,models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_rename_status_publishedsciwork_autors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='contractwork',
            name='teacher',
            field=models.ForeignKey(
                to='main.teacher',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contract_works',
                default=1,  # нужно только для миграции
            ),
            preserve_default=False,  # НЕ сохраняет default в модель!
        ),
           migrations.AddField(
            model_name='contractwork',
            name='teacher',
            field=models.ForeignKey(
                to='main.teacher',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contract_works',
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scimethodicalwork',
            name='teacher',
            field=models.ForeignKey(
                to='main.teacher',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sci_methodical_works',
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='methodicalwork',
            name='teacher',
            field=models.ForeignKey(
                to='main.teacher',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='methodical_works',
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgmethodicalwork',
            name='teacher',
            field=models.ForeignKey(
                to='main.teacher',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='org_methodical_works',
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sciresearchwork',
            name='teacher',
            field=models.ForeignKey(
                to='main.teacher',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sci_research_works',
                default=1,
            ),
            preserve_default=False,
        ),
    ]